quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=readside_admin
quarkus.datasource.password=password
quarkus.datasource.jdbc.url=jdbc:postgresql://readdb:5432/default

quarkus.rest-client.eventbus-api.url=http://eventbus:8080

quarkus.hibernate-orm.schema-management.strategy=update

filter.prefix=role

quarkus.http.cors=true
quarkus.http.cors.origins=*
quarkus.http.cors.methods=GET,POST,PUT,DELETE,OPTIONS
quarkus.http.cors.headers=*