quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=readside_admin
quarkus.datasource.password=password
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:9210/default

quarkus.hibernate-orm.schema-management.strategy=update