quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=writeside_admin
quarkus.datasource.password=password
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:9110/default
quarkus.rest-client.eventbus-api.url=http://eventbus:8080

quarkus.hibernate-orm.schema-management.strategy=update