quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=writeside_admin
quarkus.datasource.password=password
quarkus.datasource.jdbc.url=jdbc:postgresql://writedb:5432/default

quarkus.rest-client.eventbus-api.url=http://eventbus:8080

quarkus.hibernate-orm.schema-management.strategy=update

quarkus.http.cors=true
quarkus.http.cors.origins=http://localhost:63342
quarkus.http.cors.methods=GET,POST,PUT,DELETE,OPTIONS
quarkus.http.cors.headers=accept,authorization,content-type,x-requested-with